baseurl = "https://keraton.github.io"
languageCode = "en"
title = "Blog | Keraton"
theme = "Hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/bosangjay\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/keraton/\" target=\"_blank\">Github</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> â™¥"
publishDir = "docs"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Your description here"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "Bowie Brotosumpeno"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/keraton"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/bosangjay"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://www.linkedin.com/in/bowie-brotosumpeno-80ba38aa/"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

